### ISSUE TITLE
Symbol triggers not offering suggestions

### ISSUE THREAD

**Issue by forby** [selvinortiz/twig-for-craft-2#10]
The first three generic triggers (`}}`, `%%` and `##`)aren't offering any suggestions or completions. Is this a limitation of Code and symbol characters for suggestions, or is this an extension fix?

**Comment by paul-frost** [comment]
Having the same issue. I have the whatwedo Twig syntax highlighting installed as well.

**Comment by frankharrison-wj** [comment]
Yep also just spotted this – would be nice to have those working. Otherwise a great extension!

**Comment by badi365** [comment]
Same issue here.

**Comment by selvinortiz** [comment]
I'll be discontinuing development of this extension. I recommend this extension that builds on my extension's functionality.

https://marketplace.visualstudio.com/items?itemName=mblode.twig-language-2
