### ISSUE TITLE
Using editor.comment.commentLine to un-comment lines leaves spaces behind

### ISSUE THREAD

**Issue by carlcs** [selvinortiz/twig-for-craft-2#8]
Un-commenting the following lines:

```Twig
{# <p>
    {{ entry.body }}
</p> #}
```

yields to:

```Twig
 <p>
    {{ entry.body }}
</p> 
```

(there’s a space behind the closing `</p>` tag)

**Comment by selvinortiz** [comment]
Thanks Carl, I will take a look.

**Comment by carlcs** [comment]
I just noticed that whatwedo/vscode-twig is providing line comment feature on my setup, so I moved the issue https://github.com/whatwedo/vscode-twig/issues/12
