### ISSUE TITLE
How to enable tab triggers?

### ISSUE THREAD

**Issue by delixyr** [selvinortiz/twig-for-craft-2#9]
I tried all settings but I am not able to activate tab triggers in VS Code. Works fine with sublime version.

update : figured it out! Forgot to change the language to html twig. This doesnt work with .twig files ?

**Comment by selvinortiz** [comment]
Hi @delixyr, do you have a twig language package like `whatwedo.twig` installed by chance?

**Comment by delixyr** [comment]
Yes I have installed whatwedo twig highlight package. It is working for now. Earlier I did not install whatwedo thinking that craft-twig had twig syntax highlighting like sublime > view > syntax > craft-twig and it turns on tab triggers for craft-twig package for sublime. So this package for VS code requires whatwedo for highlighting and triggers to work , right? 

------
In sublime if we install php-twig tmbundle, there will eb another html-twig shown i syntax highliting in addition to craft-twig. This package doesn't have an highlighting feature?

**Comment by bdielman** [comment]
@selvinortiz - Having a similar issue as @delixyr. Just installed VS Code and grabbed the `whatwedo.twig` and your extension. Some tab completion works like `setb` and `include`, but others like `set`, `%%`, and `}}` don't. Just checking to see if I'm missing anything.

Thanks!

**Comment by selvinortiz** [comment]
I'll be discontinuing development of this extension. I recommend this extension that builds on my extension's functionality.

https://marketplace.visualstudio.com/items?itemName=mblode.twig-language-2
